site_name: Ascend GitHub Action Runners
site_url: https://ascend-gha-runners.github.io/docs/
repo_name: ascend-gha-runners/docs
repo_url: https://github.com/ascend-gha-runners/docs
edit_uri: blob/main/docs/
theme:
  name: material
  logo: assets/logo/logo.png
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  generator: false
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/tablesort.js
  - javascripts/cluster-map.js
  - javascripts/problem-report.js

plugins:
  - search
  - glightbox

markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  # - mdx_truly_sane_lists
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
nav:
  - Home:
    - Getting Started: index.md
    - Future Plans: "#future-plans"
  - GitHub Actions Guide:
    - English: user-manual-gha-en.md
    - 中文: user-manual-gha-zh.md
  - Buildkite Guide:
    - English: user-manual-buildkite-en.md
    - 中文: user-manual-buildkite-zh.md
  - Integrated Repos: Repo.md
  - Cluster Map: Cluster.md
  - Features: feature.md
  - Job Failure Reference: error-types.md
